services:
  pea-portfolio:
    image: ghcr.io/sargo22341-prog/pea-portfolio:latest
    environment:
      TZ: ${TZ:-Europe/Paris}
      PUBLIC_URL: ${PUBLIC_URL:-}
      TRUST_PROXY: ${TRUST_PROXY:-false}
      LOGO_DEV_API_KEY: ${LOGO_DEV_API_KEY:-}
    volumes:
      - /data:/app/data
    ports:
      - "4000:4000"
    restart: unless-stopped
